[program:multitest-schedule]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/multitest_uz_usr69/data/www/multitest.uz/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/multitest_uz_usr69/data/www/multitest.uz/storage/logs/schedule.log
stopwaitsecs=3600

